name: Publish cdf-typescript

on:
  push:
    branches:
      - "main"
    paths:
      - "core/typescript/package.json"
      - ".github/workflows/publish_cdf-typescript.yml"

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: core/typescript

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instal Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
      - name: Generate Docs
        run: npm run doc:html
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: core/typescript/package.json
