name: Release via release-please
on:
  push:
    branches:
      - main

permissions: write-all

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          monorepo-tags: true
