name: Release via release-please
on:
  push:
    branches:
      - main

permissions: write-all

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          monorepo-tags: true
  extra-steps-cdf-typescript:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: core/typescript

    steps:
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs['packages/cdf-typescript--release_created'] }}
      - uses: actions/setup-node@v3
        if: ${{ steps.release.outputs['packages/cdf-typescript--release_created'] }}
        with:
          node-version: 16
      - name: Instal Dependencies
        if: ${{ steps.release.outputs['packages/cdf-typescript--release_created'] }}
        run: npm ci
      - name: Run Tests
        if: ${{ steps.release.outputs['packages/cdf-typescript--release_created'] }}
        run: npm run test
      - name: Generate Docs
        if: ${{ steps.release.outputs['packages/cdf-typescript--release_created'] }}
        run: npm run doc:html
      - uses: JS-DevTools/npm-publish@v1
        if: ${{ steps.release.outputs['packages/cdf-typescript--release_created'] }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: core/typescript/package.json
          access: public
